# Site settings
title: Mr. Turtle
subtitle: by Gis Lab Marburg
website: https://www.uni-marburg.de/de/fb19/fachgebiete/phy-geo/umweltinformatik
description: Constructing a remotely controled swimming platform stuffed with sensors for environmental remote sensing
baseurl: #
url: "" # the base hostname & protocol for your site
author: Christoph Reudenbach und Thomas Nauss

# Social settings
500px_url:
facebook_url: https://www.facebook.com/GeographieMarburg/?__xts__[0]=68.ARByJXKgoGm67n00NuEP-DDyz0d4PSCu6Xyd6cmr2NkgpFWDaCtrxLNh8lVMlsMa4Msa_39XkkKgX0XEPqCUq8Mr5jsoskUMFNMKZ9vJXzNSS4DxY6TlBBuTyjWcbRQx0CzAQFwR5wkBcKY8CyRvfP5thquDOxNYPQl3YAfyf-SNVCAhVeeZ
github_url: https://github.com/gisma/boatOne/tree/master/Lidar-Lite-master

# Build settings
markdown: kramdown

port: 4002
